kind: Deployment
apiVersion: apps/v1
metadata:
  name: sw-boardgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sw-boardgame
  template:
    metadata:
      labels:
        app: sw-boardgame
    spec:
      containers:
      - name: sw-boardgame
        image: danielkomjati/sw_bg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: "300m"
          limits:
            memory: "500Mi"
            cpu: "600m"
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: sw-boardgame
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    app: sw-boardgame

